baseURL: "myweb.com/go-cricket"
languageCode: "en-us"
title: "Go Cricket"
theme: ""
archetypeDir: arch
refLinksErrorLevel: "WARNING"
refLinksNotFoundURL: "http://www.google.com"
summaryLength: 10
hasCJKLanguage: true
truncate: true
permalinks:
 url-management: /:monthname/:year/:slug
buildDrafts: true
taxonomies:
 tag: tags
 category: categories
 media: medias
 platform: platforms
 league: leagues
copyright: © 2022 Movie Times.  <a href="https://creativecommons.org/licenses/by/4.0/">Some rights reserved</a>.
params:
  developer: edwin
  team: lamp
  alterlink: "help desk"
  custom_css: "css/style.css"
  cutom_nav_css: "css/custom-nav.css"
  custom_js: "js/task.js"
markup:
  tableOfContents:
     endLevel: 6
     startLevel: 1
disableLiveReload: false
relativeURLs: true
enableInlineShortcodes: true
sectionPagesMenu : user_nav
menu:
  menusample:
   - name: Download
     pageRef: download
     weight: 4
 
paginate: 5
paginatePath: page
enableGitInfo: true
rssLimit: 20
author:
 - name: joey
 - email: joey@gmail.com
resources:
 - src: "movie/java.jpg"
enableEmoji: true
ignoreErrors: my-custom-error
enableRobotsTXT: true

