baseURL: ""
languageCode: "en-us"
title: "New Site"
theme: ""
archetypeDir: arch
refLinksErrorLevel: "WARNING"
refLinksNotFoundURL: "http://www.google.com"
summaryLength: 80
hasCJKLanguage: true
truncate: true
permalinks:
 url-management: /:monthname/:year/:slug
buildDrafts: true
relativeURLs: true
