baseURL: ""
languageCode: "en-us"
title: "New Site"
theme: ""
archetypeDir: arch
refLinksErrorLevel: "WARNING"
refLinksNotFoundURL: "http://www.google.com"
summaryLength: 10
hasCJKLanguage: true
truncate: true
permalinks:
 url-management: /:monthname/:year/:slug
buildDrafts: true
relativeURLs: true
taxonomies:
 tag: tags
 category: categories
 media: medias
disableLiveReload: false
copyright: © 2015 Jane Doe.  <a href="https://creativecommons.org/licenses/by/4.0/">Some rights reserved</a>.
params:
  developer: edwin
  team: lamp
  alterlink: "help desk"
markup:
  tableOfContents:
     endLevel: 6
     startLevel: 1
# disableKinds:
#  - taxonomy
#  - term