baseURL: ""
languageCode: "en-us"
title: "Movie times"
theme: "PaperMod"
archetypeDir: arch
refLinksErrorLevel: "WARNING"
refLinksNotFoundURL: "http://www.google.com"
summaryLength: 10
hasCJKLanguage: true
truncate: true
permalinks:
 url-management: /:monthname/:year/:slug
buildDrafts: true
relativeURLs: true
taxonomies:
 tag: tags
 category: categories
 media: medias
 platform: platforms
disableLiveReload: false
copyright: © 2022 Movie Times.  <a href="https://creativecommons.org/licenses/by/4.0/">Some rights reserved</a>.
params:
  developer: edwin
  team: lamp
  alterlink: "help desk"
markup:
  tableOfContents:
     endLevel: 6
     startLevel: 1
