baseURL: ""
languageCode: "en-us"
title: "Movie times"
theme: "PaperMod"
archetypeDir: arch
refLinksErrorLevel: "WARNING"
refLinksNotFoundURL: "http://www.google.com"
summaryLength: 10
hasCJKLanguage: true
truncate: true
permalinks:
 url-management: /:monthname/:year/:slug
buildDrafts: true
relativeURLs: true
taxonomies:
 tag: tags
 category: categories
 media: medias
 platform: platforms
copyright: © 2022 Movie Times.  <a href="https://creativecommons.org/licenses/by/4.0/">Some rights reserved</a>.
params:
  developer: edwin
  team: lamp
  alterlink: "help desk"
  custom_css: "css/style.css"
markup:
  tableOfContents:
     endLevel: 6
     startLevel: 1
disableLiveReload: false
relativeURLs: true
enableInlineShortcodes: true
sectionPagesMenu : main
menu:
 user_nav:
  - identifier: other
    name: others
    weight: 4
    url: /platforms
  - identifier: help
    name: help
    parent: other
    url: /platforms/hotstar
  - identifier: query
    name: query
    url: /platforms/netflix
    parent: other
paginate: 3
enableGitInfo: true

